### ISSUE TITLE
WebApps charter: Implementor interest

### ISSUE THREAD

**Issue by LJWatson** [w3c/charter-drafts#157]
>All specification must have least two implementors willing to commit to collaborating on the specification. If there is only a single implementer willing to implement the specification for a prolonged period (e.g., 6 months), the specification shall be moved to the WICG for incubation. If the specification gains traction with multiple implementors, it can be moved back into the working group.>

The intent of this is good, but I'm concerned about the specifics...

Is "willing to commit to collaborate" the same as "willing to implement"?

What does this actually look like? Is it a public statement of intent to implement; active participation in the development of the spec; something else?

Can we put a time constraint on this, knowing that we'd need to recharter every time we wanted to transfer something in or out of the WG.

What advantage does this give us, over requiring at least two implementations in order to exit CR?

**Comment by LJWatson** [comment]
Ping @marcoscaceres and @chaals

**Comment by chaals** [comment]
(I try to avoid the word shall, FWIW).

Hmm. Agree with the concern about not wanting to recharter every few months (because unfortunately that is still much more painful than it should be - in an ideal world that would not be true and I would be fine).

I think it makes sense to want more than one implementor willing to work on the spec, but I agree with @LJWatson that it isn't clear what that looks like in practice. People tend not to work on specs week-in week-out, and measuring commitment it not as easy as it sounds.

(The advantage over requiring multiple implementations to exit CR is that we don't spend 2 years working on something that only one person is really interested in, before we discover there is no way it will meet that criterion).

**Comment by marcoscaceres** [comment]
@LJWatson wrote, 
> Is "willing to commit to collaborate" the same as "willing to implement"?

I don't think we can go as far as willing to implement, because some companies won't reveal that - but they do give positive signals or actively work together on things. 

> What does this actually look like? Is it a public statement of intent to implement; active participation in the development of the spec; something else?

For the payment specs, we ask a public commitment to implement. This usually takes the form of a link to a bug tracker (e.g., bugzilla for Mozilla) or some kind of public comment, like teleconference minutes. An actual link to a bug is preferred, of course, as we can then track progress.    

Sometimes we take a link to a comment on GitHub as a public signal.

> Can we put a time constraint on this, knowing that we'd need to recharter every time we wanted to transfer something in or out of the WG.

Not sure...  @plehegar, how does Web Perf deals with this (moving stuff into/out-of WICG)? 

> What advantage does this give us, over requiring at least two implementations in order to exit CR?

We (Chairs and Team) don't waste cycles on any specs that are not going anywhere. If stuff is not moving, we just tell them to go and incubate.

**Comment by marcoscaceres** [comment]
@chaals  wrote: 
> I think it makes sense to want more than one implementor willing to work on the spec, but I agree with @LJWatson that it isn't clear what that looks like in practice. People tend not to work on specs week-in week-out, and measuring commitment it not as easy as it sounds.

No, I promise you it's easy. Look at this pull request and the links to the bug tackers:  https://github.com/w3c/payment-request/pull/765

Literally just drop a link in and check a box. It's not very hard and it's the least people can do.

If Editors can't get two implementation commitments for things, then those things can't land in the spec. It's that simple.  

> The advantage over requiring multiple implementations to exit CR is that we don't spend 2 years working on something that only one person is really interested in, before we discover there is no way it will meet that criterion.

Right, this protects against that, because it means nothing can land in the spec unless there is implementation commitment ;) Single vendor things just end up "at risk" and can be removed as part of CR. See:
https://github.com/w3c/payment-request/pull/794

No trauma, no drama... just smooth sailing ⛵️.

**Comment by marcoscaceres** [comment]
So, irrespective, of my last comment - I think dropping what I proposed about the WICG might just be what happens in practice (or we just move things to be a Note if things stop moving). I'm going to remove what I wrote.
