### ISSUE TITLE
WebApps charter: Test suite completion

### ISSUE THREAD

**Issue by LJWatson** [w3c/charter-drafts#158]
>Each specification must have a publicly accessible test suite and, during the Candidate Recommendation phase, an implementation report. The test suite should be developed in parallel to the specification and must be fully and demonstratively completed before the specification can progress pass the Candidate Recommendation phase.>

The current WebPlat charter requires that the test suite be completed before entering CR, but this text changes that so the test suite is required to exit CR.

There are pros and cons for each approach. I don't feel strongly either way, though having the test suite complete before entering CR does lend itself better to the idea of test driven spec development.

Flagging it here to make sure we choose the right one.

**Comment by LJWatson** [comment]
Ping @marcoscaceres  and @Chaals

**Comment by chaals** [comment]
"fully and demonstratively complete"?

I'm not sure that we should require a test suite before CR. It is a good practice, but especially as phrased this front-loads a pile of work that could be usefully done *during* CR in fleshing out details. Besides which, demonstrating a test suite is complete is a bit of a fools' errand in most cases I've seen for Web Standards, since it pretty much negates the purpose of continually evolving specs...

**Comment by marcoscaceres** [comment]
@LJWatson wrote: 
> There are pros and cons for each approach. I don't feel strongly either way, though having the test suite complete before entering CR does lend itself better to the idea of test driven spec development.

Exactly. Why I do feel strongly about it. I've been burnt by this too many times :( 

@chaals wrote:
> I'm not sure that we should require a test suite before CR. It is a good practice, but especially as phrased this front-loads a pile of work that could be usefully done during CR in fleshing out details. 

The problem is that significant bugs are *always* found during creation of the test suite. That makes makes a huge mess for editors, lawyers, chairs, the w3c team, documentation teams, etc. 

Spec bugs will, of course, be found during CR: that's what CR is for - but having a fairly complete test suite done before entering CR greatly reduces the number of spec bugs. 

> Besides which, demonstrating a test suite is complete is a bit of a fools' errand in most cases I've seen for Web Standards, since it pretty much negates the purpose of continually evolving specs...

Depends how the standard is developed - but generally it's not a problem if the spec is test-driven, because "no test, no merge" means: 

 1. each  modification to spec MUST be reflected in the test suite, so demonstrating that each change has a test becomes trivial. For example: https://github.com/w3c/payment-request/pull/776. 
 1. It's possible to include a link to each test directly into the spec - thus again making it possible to see what's tested in and what's not. You can see this in the Editor's draft Payment Request spec: each conformance requirement has a link to its test.

**Comment by LJWatson** [comment]
As I mentioned above, the current WebPlat charter already has this as a requirement:
>A comprehensive test suite for all features of a specification is necessary to ensure the specification's robustness, consistency, and implementability,
and to promote interoperability between User Agents. Therefore, each specification must have a companion test suite, which should be completed before transition
to Candidate Recommendation, and must be completed, with an implementation report, before transition from Candidate Recommendation to Proposed Recommendation.
Additional tests may be added to the test suite at any stage of the Recommendation track, and the maintenance of a implementation report is encouraged.

When I was putting together the first draft of the WebApps charter, I tried hard to reduce the verbosity. We heard feedback at the AC meeting in Beijing, that charters were difficult to read, and consequently harder to review. So perhaps something like this:

>Each specification will have a comprehensive test suite available before transition to Candidate Recommendation. The test suite will be used to produce an implementation report before the specification transitions to Proposed Recommendation.>

**Comment by marcoscaceres** [comment]
Like it! Will send a PR.
