### ISSUE TITLE
WebApps charter: Browser implementations

### ISSUE THREAD

**Issue by LJWatson** [w3c/charter-drafts#159]
>Each specification must have at least two independent implementations in web browsers in order to progress to Proposed Recommendation.>

Do we want to restrict this to web browsers? Browsers are the most likely source of implementations, but restricting it to browsers seems like an un-necessary constraint.

**Comment by LJWatson** [comment]
Ping @marcoscaceres  and @Chaals

**Comment by chaals** [comment]
No, I don't think such a restriction is a good idea.

**Comment by marcoscaceres** [comment]
Can expand it. I just don’t want rando toy implementations counting. We need real software that actual people use, and not research projects or anything like that.

**Comment by chaals** [comment]
@marcoscaceres said

> We need real software that actual people use, and not research projects or anything like that.

Agreed. But "browsers" is a pretty inaccurate proxy for that. I think we should be clearer about what we really mean.

**Comment by marcoscaceres** [comment]
@chaals, sure - let me see if I can find some suitable text from other charters or can craft something up. 

I guess a larger question is: are any of the deliverables NOT specifically targeted at web browsers? Or, alternatively, would any deliverables be blocked from progressing along the Rec Track because they are not implemented in a web browser? 

I can't see any from our deliverables list that would not require a browser (or AT acting as a browser) implementation to become a Recommendation - however, if I've overlooked some deliverables, let me know.

**Comment by LJWatson** [comment]
Perhaps we can simplify things... if we require at least two statements of intent to collaborate/implement for all specs transitioning into the WG, and team that up with the requirement to have at least two implementations for each feature in a spec, does that do the trick?

Do we think there are specs (in the current charter) that do nnot meet the first of these criteria?

**Comment by marcoscaceres** [comment]
@LJWatson: 
> Do we think there are specs (in the current charter) that do not meet the first of these criteria?

* ARIA in HTML. 
* Using ARIA

Because they are authoring guidelines. The rest seem ok.

**Comment by marcoscaceres** [comment]
Let's go with what CSS WG uses:

"The work is considered a success if there are multiple, independent, interoperable implementations of its specifications that are widely used."

The "widely used" alleviates my concern about polyfills - while "implementations" is wide enough to encompass ATs and browsers.
