### ISSUE TITLE
[svg-2019] term defined in external, unstable document

### ISSUE THREAD

**Issue by frivoal** [w3c/charter-drafts#185]
Pragraph 2 of section "2 Deliverables " of https://w3c.github.io/charter-drafts/svg-2019.html says:

> The SVG WG will follow a test as you commit approach to specification development.

With a link to https://github.com/w3c/testing-how-to/#test-as-you-commit-pointer-event-whatwg-webperf to define "test as you commit".

That document is can be changed without an AC ballot (and also, incidentally, is not hosted on w3.org).

Charters should be stable and self contained. That definition should be inlined.

**Comment by svgeesus** [comment]
All CSS WG drafts can be changed without an AC ballot and are not hosted on w3.org; the web still runs on them just fine.

There is a tendency to move documents like this off the w3.org site (and especially, off Member space) and host them on GH instead, precisely so that issues can be raised and tracked.

The link is wrong btw, it should be [https://github.com/w3c/testing-how-to/#test-as-you-commit](https://github.com/w3c/testing-how-to/#test-as-you-commit) but PLH fixed that in the template yesterday, so the same edit can be made to the SVG charter.

**Comment by frivoal** [comment]
Editors draft are not supposed to need an AC ballot. So it is OK for them to be possible to update without an AC ballot.

Charters are supposed to need an AC ballot. It is not OK for them to normatively depend on things that can be changed arbitrarily.

As for the domain:
* Editor's draft have no status, it's not all that important
* csswg.org could be transfered to the W3C if its current host gave up on maintaining it. github.com cannot.

**Comment by plehegar** [comment]
I can see the issue with referencing wording in a document that has no standing and can be changed anytime.  Short of copy/paste the text in the charter, I don't see a solution at the moment but will keep thinking. I can also imagine that some charters might tweak the text to accommodate different cases.

**Comment by frivoal** [comment]
> Short of copy/paste the text in the charter, I don't see a solution at the moment but will keep thinking.

That would be appropriate.

We could also have that text in something like the Process, and I think that'd be OK to refer to from charters, but as you say "I can also imagine that some charters might tweak the text to accommodate different cases", so I don't actually support hard-coding it in the process, and would prefer in-lining things in the charter.

**Comment by plehegar** [comment]
I made a copy of the existing testing policy at
  https://www.w3.org/2019/02/testing-policy.html
It's signed by Ralph and me on behalf of the Director, making it clear that no change can't be made since it's been looked at by the AC (ie if a Group wants a different policy, they'll have to fork the document).

So, the proposal is to replace the link in the charter with a link to that new document.

Is it acceptable?

**Comment by frivoal** [comment]
I think in-lining would be better, as this approach decreases the likeliness that this normative text will actually be reviewed by those reviewing the charter. I am also unsure what the benefit of having charters informatively depend on documents whose maintenance mode is undefined by the process.

With that said, the guarantees offered in the status section of that document are an improvement over linking to the github readme, so despite my lack of enthusiasm, I agree it is an improvement.

----

PS: hyperlinks go from source to target, and are not bidirectional. So finding "Group Charters it is linked from" to be able to poll the AC might end up being a cumbersome exercise.

**Comment by svgeesus** [comment]
Fixed (link to new doc, plus blockquote from that doc with cite) for [SVG charter](https://www.w3.org/Graphics/SVG/svg-2019.html).

Charter template not updated (yet) as this is an opt-in polic at this stage. Though it could be added in a `fixme` section so those adopting it do so consistently.
