### ISSUE TITLE
[svg-2019] Timeline unrealistic

### ISSUE THREAD

**Issue by frivoal** [w3c/charter-drafts#188]
The [charter](https://w3c.github.io/charter-drafts/svg-2019.html) expects an SVG2 REC in Oct 2019. The seems very unrealistic to me. The [svg directory of the wpt project](https://github.com/web-platform-tests/wpt/tree/master/svg) is starting to show a decent number of tests [1], but that still falls far short of the amount that will be needed for such a large specification. This alone seems enough to doubt that the Q3 / October deadline will be met.

If the timeline is just a placeholder that everybody will ignore, it should be deleted. If the WG's success or failure will be judged based on meeting this deadline, the group is setting itself up for failure.

----
[1] quick estimate of the number of test cases for SV2 given by:
```sh
$ cd wpt/svg && tree -I "import|*-ref*|*.js|resources|support|*.yml|*.md"
[...]
303 files
```
That's not bad, and shows the group has been working. But, for reference, here's a spec of comparable size: CSS2.1:
```sh
$ cs wpt/css/CSS2 && tree -I "*-ref*|*.js|resources|support|*.yml|*.md|Makefile|css1|*README|reference"
[...]
9701 files
```

**Comment by ewilligers** [comment]
I believe the goal is to have tests for features added since SVG 1.1. 

See issues marked [Test suite](https://github.com/w3c/svgwg/labels/Test%20suite) for the tests we believe are needed.

**Comment by svgeesus** [comment]
As the charter states:

> Test suite and implementation report for the SVG2 specification, **concentrating on changes relative to SVG 1.1 Second Edition**

**Comment by frivoal** [comment]
Sure, and the difference between SVG1.1 and SVG2 is much smaller than between CSS1 and CSS2, so this is not a perfect comparison. Even then, 300 tests as you have now is around the amount that's appropriate for a small specification like css-ui. You may not need over 9000 tests, but you'll certainly need many more than what you currently have. I'll be the first to be delighted if we can wrap this up in less than a year, but previous charters stated dates which I thought were similarly optimistic, and missed them. Giving it the full duration of the charter would be in my opinion still somewhat optimistic, but much more plausible.

**Comment by svgeesus** [comment]
By the way, the frozen CSS 2.1 testsuite was written well before the javascript harness (which can test, say, 300 element/attribute or element./property combinations in 300 subtests of one overall test , rather than 300 separate tests) was written.

It would be great to have the luxury of another 10 years to fully and exhaustively test the entire SVG spec. However, we need an SVG2 base which SVG modules can build on. In one form or another, attempts to provide functionality to SVG beyond SVG 1.0 have been going on since 2000. That is **19 years**. We need to stabilize SVG2, then address new functionality which is currently stalled.

In the same way that CSS 3,4,5 modules extend, clarify, or replace portions of CSS 2.1, SVG modules are likely to do the same.

**Comment by svgeesus** [comment]
> See issues marked Test suite for the tests we believe are needed.

See also the [`Needs tests`](https://github.com/w3c/svgwg/labels/Needs%20tests) tag.

**Comment by frivoal** [comment]
I agree spending another decade or 2 on getting SVG to REC isn't useful. I am also on the record for being in favor of modularizing SVG in a way that is similar to CSS, and agree that this would enable faster revving up of the various parts. I remain highly skeptical that we can do what the charter says in the time it claims we'll do it, but oh well. As long as we do the work, I'm good.

What I think would be really unfortunate is that if we say we're going to be done in 5 months (that's when the charter says PR for SVG2 is due), make good progress, but (predictably, IMO) fail to make enough progress to reach that milestone, and then use that fact to declare the WG a failure.

**Comment by AmeliaBR** [comment]
FYI, the [timeline in the final approved charter](https://www.w3.org/Graphics/SVG/svg-2019.html#timeline) was adjusted after this issue was posted.  (It will remain to be seen whether we can live up to the revised dates!)

Either way, the issue can probably be closed as the charter is no longer under discussion.
