### ISSUE TITLE
[svgcg-2019] Extend scope to cover some non-spec activites?

### ISSUE THREAD

**Issue by BigBadaboom** [w3c/charter-drafts#205]
I can think of some potential activities for the community group that are not currently listed, but could potentially be within the scope of an SVG CG and add value to the SVG community at large.  These are not specifically related to the SVG standard itself, but to the usage of it by third parties, especially authoring tools and  applications..

For example:

- Recommendations on the generation of SVG files from third party software (ie export filters)
     - presentation attributes, vs style attributes, vs style elements
     - numerical accuracy of coordinate values
     - how to convert features unsupported by the current SVG standard (eg rasterisation vs processed vectors etc)

- Recommendations on storage of editor metadata in SVG files
   - eg datalist vs namespaced attributes vs metadata element etc

- In addition to feature polyfills, which are already in the draft, we could also consider including:
   - format conversion libraries
   - path processing (eg. flattening, boolean operations on paths)
   - etc

**Comment by AmeliaBR** [comment]
Hi Paul,

I definitely agree that these are all good activities for the working group.  I think all of these items are in scope with the charter as written, but we could probably be more explicit; the charter template focuses on specifications because that is where the IP issues are, but that doesn't mean that needs to be the main focus.

Suggestions for integrating your points into the charter draft:

1. In the first part of the [“Scope of Work"](https://w3c.github.io/charter-drafts/svgcg-2019.html#scope), break the bullet list into three parts:

   > The community group will support the standardization and adoption of Scalable Vector Graphics (SVG) through three types of work:
   > 
   > - Incubating proposed specifications for extensions and integrations to SVG.
   > - Hosting projects for developing SVG-related software.
   > - Compiling non-normative reports about the use of SVG and vector graphics.
   > 
   > See [Deliverables](https://w3c.github.io/charter-drafts/svgcg-2019.html#deliverables) for examples of in-scope work.

2. Under [“Deliverables — Non-Normative Reports”](https://w3c.github.io/charter-drafts/svgcg-2019.html#non-normative-reports), expand the "in particular" paragraph:

   > The group may produce other Community Group Reports, that are within the scope of this charter but that are not Specifications, for instance use cases, requirements, white papers, or best-practices guides. 
   > 
   > In particular, the draft SVG Authoring Guide could be completed under the scope of the community group.  A separate best practice guides could provide guidance for SVG authoring tools and other software that exports or manipulates SVG files.  Use-case and requirements reports could review how SVG and other vector graphics languages are being used, separate from any specification proposal.

3. Under [“Test Suites and Other Software”](https://w3c.github.io/charter-drafts/svgcg-2019.html#test-suites), broaden the bullet point about "debugging and authoring tools":

   > - Debugging and authoring tools (stand-alone or extensions to existing software) to make it easier for content creators to use SVG, including tools that promote best practices with existing SVG technologies, tools to support the adoption of new features, and tools for experimenting with feature proposals.


Do you think that covers your points?

**Comment by BigBadaboom** [comment]
Hi Amelia

Yes I think so. LGTM

Thanks
