### ISSUE TITLE
Charters should be explicit about allowing a group to propose Recommendations that allow new features

### ISSUE THREAD

**Issue by swickr** [w3c/charter-drafts#274]
Though Process 2020 allows a Working Group to wait until Proposed Recommendation to declare that it wishes to [allow new features to be incorporated](https://www.w3.org/2020/Process-20200915/#revised-rec-features) in future Recommendations, whether to permit the Group to request that option for any of its deliverables can be a factor during review of a proposed charter.

It would be useful for the charter template to include suggested boilerplate to identify deliverables that are anticipated to be proposed as such living standards.

**Comment by svgeesus** [comment]
The process doc does not use the term living standard, so the template should not either to avoid confusion.

This looks like a MAY requirement, to give a heads-up that some deliverable is expected to allow new features. Process only says that this has to happen at Proposed Rec stage.

Is this new "allow new features" expected to replace publishing errata, or to supplement that process, or to allow more wide-ranging errata?

[process is unclear](https://www.w3.org/2020/Process-20200915/#transition-pr) because it starts off talking about proposed rec but then says if there are any changes the document has to go to CR first.

**Comment by svgeesus** [comment]
Discussed on 8 Dec 2020 Strat call. It was felt that putting this in the charter was not a good idea; groups can decide on a case by case basis when a particular specification goes to Proposed Rec, and the AC has a chance to weigh in at that time. Thus, strat preferred to close with no action.

**Comment by svgeesus** [comment]
Since we resolved to close with no action, I guess this should be closed.
