### ISSUE TITLE
[template] remove reference to publication status page

### ISSUE THREAD

**Issue by samuelweiler** [w3c/charter-drafts#297]
The template includes: "More detailed milestones and updated publication schedules are available on the group publication status page."  with a link pointing to a wiki

Is anyone still using this?  Should we remove it?

If we should leave it in, what should it point to?

**Comment by wseltzer** [comment]
@plehegar does Project have a recommendation or best practice here?

**Comment by plehegar** [comment]
we don't have best practices, short of our milestones tracker which hasn't been used/enforced due to its limitations. Groups are using wikis, google doc, etc to maintain this info, if they do maintain those infos. We can not put a generate link in there but keeping the sentence in the charter while allowing it to be removed when edited seems a good trade off. In other words, if such link exists, the sentence should be there with the right link, otherwise it should be removed.

**Comment by samuelweiler** [comment]
Perhaps we could point to: https://www.w3.org/groups/wg/[whatever]/publications ?

**Comment by samuelweiler** [comment]
strat call 2 march 2021 suggests yes, that is a reasonable default.
