### ISSUE TITLE
[template] consolidate testing lines

### ISSUE THREAD

**Issue by samuelweiler** [w3c/charter-drafts#299]
We have two testing lines, separated by an unrelated item. 

- There should be testing plans for each specification, starting from the earliest drafts.
- Consider adopting a healthy testing policy, such as: To promote interoperability, all changes made to specifications should have tests.

They should be combined, perhaps by striking the first one, modifying the second to say "all features" rather than  "all changes", and putting the second in by default.

**Comment by astearns** [comment]
I would prefer to keep the “all changes” wording, as that encourages testing as the specification is developed rather than waiting for the final text and finding out some assumption everything’s built on is wrong.

So perhaps the first bullet could be about a plan for testing every feature, and the second bullet could be about keeping tests up-to-date and/or to validate spec changes?

**Comment by svgeesus** [comment]
Yes, I agree with @astearns that these two items have related, but different, intents. The suggested merger obscures that, and the existing text is the result of multiple AC reviews.

**Comment by svgeesus** [comment]
Closed as no consensus to make the change
