### ISSUE TITLE
[template] multiple place for brief description and backgound?

### ISSUE THREAD

**Issue by himorin** [w3c/charter-drafts#383]
current template has three places to put mission/background/description as:

> The mission of the [name] (Working|Interest) Group is to [do something cool and specific on the Web].
at the top (right below the group name as title)

> Brief background of landscape, technology, and relationship to the Web, users, developers, implementers, and industry.
at right below of group summary table, before 1. Scope section

and, there is one section `1. Scope` to briefly describe scope of group.

In most cases, (at least) contents for former two places should be similar or the same, since landscape, technology, and relationship to the Web should be stated as mission of group, and groups are required to have the same (or similar) text to the two places if group aligns with the template.
It seems, we are better to remove one at right below of group summary table.

**Comment by svgeesus** [comment]
The mission is typically a single sentence while the background should give more detail.

The scope and background used to be the same section but feedback from charter reviewers, in particular legal, was that the scope section should be short and avoid background discussion.

**Comment by svgeesus** [comment]
However I agree that an actual section heading would make it clearer where to but general background description. Some charters have already been adding such a header.

**Comment by svgeesus** [comment]
Header added, clarified that the background section is where more lengthy descriptions go.

**Comment by samuelweiler** [comment]
As @himorin says above,

> In most cases, (at least) contents for former two places should be similar or the same, ...
It seems, we are better to remove one at right below of group summary table.

I can see cases where we need more verbiage, but I'm not sure we need them in all cases.  Should this section be marked as optional? Since this was merged while I was away, I won't reopen - maybe there was a consensus (e.g. on a call) not reflected in this issue, but I will be pushing back in individual cases. @himorin, what do you think?

Here's an [example](https://github.com/w3c/strategy/issues/414#issuecomment-1577337388) charter review where @svgeesus writes "It does look odd that Motivation and Background is entirely empty, although Mission kind of covers that."
