### ISSUE TITLE
[wg/did] Allow the did:web and did:key specifications to advance to CR

### ISSUE THREAD

**Issue by plehegar** [w3c/charter-drafts#428]
From @msporny:
[[
Allow the did:web and did:key specifications to advance to Candidate Recommendation but no further (in order to ensure ample implementer feedback).
]]
From [2023 AC review](https://lists.w3.org/Archives/Public/public-new-work/2023Aug/0003.html).

**Comment by msporny** [comment]
Digital Bazaar supports this.

**Comment by peacekeeper** [comment]
Considering how contentious the topic of DID methods has been, it might be better to defer to the WG to decide which DID methods it wants to specify (if any at all), rather than picking them in advance.

**Comment by mprorock** [comment]
The w3c is not the correct place for this work.  I strongly support the position taken by @or13 on the list.

**Comment by msporny** [comment]
> The w3c is not the correct place for this work. I strongly support the position taken by @OR13 on the list.

Strongly disagree that the World Wide **Web** Consortium is not the correct place for did:web, expect did:web to be forked if it goes somewhere else.

**Comment by OR13** [comment]
html forked, and it ended up being for the best.

It's a shame that DIDs have this method component in the identifier that causes people to think of the identifiers as names worth squatting on / controlling or owning.

In the case of did web, you end up having both the method and the web origin as being human friendly  / ownable concepts.

I don't think did web, should move from W3C... I think people should use URLs instead of it... If you want to put a URN inside a URL as many people do, I think that's fine also.

**Comment by rxgrant** [comment]
Both did:web and did:key are fine topics for interested parties forming new W3C WGs, but will cause blocked consensus if attempted by DID-WG, because they are inherently problematic DID Methods.

**Comment by plehegar** [comment]
The charter was [announced ](https://lists.w3.org/Archives/Public/public-did-wg/2024Apr/0000.html)
