### ISSUE TITLE
[wg/solid] choice of the proposed chairs

### ISSUE THREAD

**Issue by pchampin** [w3c/charter-drafts#455]
Concerns have been expressed that the proposed chairs:
* lack W3C experience
* may not represent the whole community
* may not ensure adequate continuity with the Community Group

From https://lists.w3.org/Archives/Public/public-new-work/2023Oct/0003.html
> In the interest of (1) guarding the W3C process, (2) bringing the Solid
project to its full potential, and (3) the business interests of the many
Solid project participants, including my own employer, the Ponder Source
Foundation, I think creating this WG without someone like Sarven as a
co-chair would be a mistake.
>
> He was also a key contributor to most of the existing documents including
Solid Protocol and Solid QA, and knows the years of thought that have gone
into these documents so far like few others. I therefore second the request
already made by several other reviewers, to invite Sarven as a 3rd
co-chair.
>
> At the same time, I value the expertise and dedication that Laurens
Debackere and Aaron Coburn will bring as co-chairs of our WG, and together
with Sarven I think they can provide a healthy mix of industry use cases
(e.g. build things that work in practice), implementer's interests (e.g.
avoid purist rabbit hole discussions), and a fair, open and constructive
process (e.g. a transparent link between specs, tests, and implementation
reports).

From https://lists.w3.org/Archives/Public/public-new-work/2023Oct/0006.html
>    We second the many comments with regards to the WG chairs. There are
definitely strong and valid concerns 1.) with regard to a focus in
standardization on one company's 
product-related work and 2.) with both nominated chairs not having shown
the willingness to value and foster the continuity of incubation work done
in the CG or similar incubation spaces. In order to ensure this continuity
and to support adherence to W3C process towards standardization in the
group, we suggest appointing the current CG chair, Sarven Capadisli, as
additional chair to the WG. Having Sarven facilitating workshops at SWIB
conference and having invited him to do the conferences's 2023 keynote, we
know him as a person bridging and helping people and educating them on
decentralized web standards but he definitely will not sell products.

From https://lists.w3.org/Archives/Public/public-new-work/2023Oct/0007.html
> We have questions about how the Team selected WG chairs without apparent
consideration of the existing CG chair. This looks improper and worth
objecting to until an explanation is made clear.

and [other reviews](https://www.w3.org/2002/09/wbs/33280/solid-wg-2023/results#xsupport) (member-visible only)

**Comment by csarven** [comment]
I published an article titled [Self-Review: Chairing](https://csarven.ca/self-review-chairing) where I reflect on my experiences as the chair of the Solid CG (since 2019) and a snapshot of history. I am sharing this for your consideration towards resolving the W3C Team Decision in the context of the Solid WG charter review.

See also:
* https://github.com/solid/specification/discussions/568
* https://www.w3.org/2023/09/13-w3process-minutes.html#x463
* https://github.com/w3c/tpac2023-breakouts/issues/43
* https://github.com/w3c/w3process/issues/281
* https://github.com/w3c/Guide/issues/185
* ["more neutral/experienced chairs (15, FO) [..] lack of experience of proposed chairs was mentioned."](https://github.com/solid/specification/blob/main/meetings/2023-10-11.md#wg-charter-proposal-status-update)
