### ISSUE TITLE
REST is a transfer protocol

### ISSUE THREAD

**Issue by mjkoster** [w3c/charter-drafts#51]
The document frames REST as a transport protocol and suggest to define abstract messaging on top of REST. REST is a transfer protocol and already embodies a well developed simple and reusable message layer. 

WoT must accommodate REST as a transfer protocol and interact with the hypermedia controls provided by underlying REST transfer systems. That there will be systems that already know how to interact using the full REST distributed state machine. WoT should not be a replacement or alternative to REST architecture, but an augmentation that enables consistent interaction across many systems at web scale.

**Comment by draggett** [comment]
Functionally WoT defines the API exposed to applications, and how this maps to specific platforms and protocols. I don't understand what you mean by WoT should not be a replacement or alternative to REST architecture".  WoT is not a new protocol, but rather a means for platforms to interoperate using the protocols they have in common. The communications metadata needs to be sufficient for one platform to know how to talk to another. I am trying to understand what this means in practice for interoperating with OCF and oneM2M based platforms.

Each platform may have its own metadata formats, but it would be nice, but not essential, to be able to map this into RDF as an interlingua for communications metadata. In some cases, platforms may not provide machine interpretable service definitions. In that case, someone will need to provide these in order for the services to be accessible via the web of things.

We do need some standard metadata that is independent of platform specific service description formats. This would allow application developers to describe their preferences for communication patterns without needing to know about the details of the protocols and formats used by particular platforms.

OCF currently supports JSON based messages via REST over CoAP as described using [RAML](http://www.baeldung.com/raml-restful-api-modeling-language-tutorial), which is a very complex file format for describing RESTful APIs. You can see an example for an [airflow control service](http://www.oneiota.org/revisions/896) on the oneiota website. I am hoping that our call with Ravi and Markus will make this clearer.

oneM2M appears to use XML or JSON based messages via REST over HTTP and CoAP. I found an [introduction on the fiware website](https://forge.fiware.org/plugins/mediawiki/wiki/fiware/index.php/ETSI_M2M_mId_Open_RESTful_API_Specification_%28PRELIMINARY%29). It starts with hierarchies of resources that are addressed using an HTTP path.  I have yet to come across a machine interpretable definition of M2M services. However the examples indicate a straightforward use of GET, PUT, POST and DELETE methods with the path referencing the resource in question. You can query (GET) or update (PUT) some or all of the resources according to the path specificity.  POST is used to create a new resource and DELETE to remove it.

In the web of things, we have properties, actions and resources, but these distinctions are blurred or lacking in M2M. My guess is that POST is needed for invoking actions, since these are expected to have side effects. It isn't clear whether the results of a POST supports a sequence of responses, e.g. through keeping the HTTP connection open. I am unclear how events can be delivered with M2M. A call back HTTP end point could be an answer.  HTTP long polling is another possibility.  The CoAP OBSERVE pattern is also possible for CoAP based M2M services.

**Comment by ashimura** [comment]
as decided during the Beijing f2f,  this comment is closed
