### ISSUE TITLE
[ig/security]

### ISSUE THREAD

**Issue by frivoal** [w3c/charter-drafts#547]
The draft charter says:
> SING may provide input to the W3C Process Community Group on process changes that will improve security in Web standards

As the Process CG acts under delegation from the AB, I wonder if it wouldn't be better to reference the AB directly here instead.

**Comment by simoneonofri** [comment]
hi @frivoal

thanks for the comment. I will prepare the PR.

Also, in general, since we're already doing reviews with those who are interested in joining the group, the issue is that it's true that the review is a specific moment, but let's say it's the concluding part of a series of activities (Threat Modeling, writing Security Considerations) that come first (often from the Explainers).

**Comment by simoneonofri** [comment]
addressed here, we can follow-up the discussion in the PR https://github.com/w3c/strategy/issues/449
