### ISSUE TITLE
[procedural strategy] being notified when the charter changes?

### ISSUE THREAD

**Issue by iherman** [w3c/charter-drafts#602]
Is there a way to be notified when the charter template changes? I begin to work on a new charter, and the cycle of updating the template seems to be smaller than the one needed by the development of a charter itself. The result is that one has to reconcile the charter with the template at the very last step, which is a pain...

**Comment by svgeesus** [comment]
It is a pain, yes.

When the charter template was first being developed, I suggested that the system should be database-driven so that per-group information would be merged with the template to auto-generate a draft charter. Thus, manual editing and reconciliation would be eliminated.

At the time, that was felt to be too much (development) work and so we have the current system where most charters need careful review to make sure they follow the current template. Which is a pain.

To track changes, the [template history](https://github.com/w3c/charter-drafts/commits/gh-pages/charter-template.html) is useful.

**Comment by iherman** [comment]
> It is a pain, yes.
> 
> When the charter template was first being developed, I suggested that the system should be database-driven so that per-group information would be merged with the template to auto-generate a draft charter. Thus, manual editing and reconciliation would be eliminated.
> 
> At the time, that was felt to be too much (development) work 

It is, but a pity it was not done.

I was wondering whether, at least, a respec-like tool would not be possible. Most of the charter is boilerplate or data, except for the scope section, abstract and background...

> and so we have the current system where most charters need careful review to make sure they follow the current template. Which is a pain.

Actually, the worst is to go through the Group->Strategy->TiLT review process which may be longer than the next template cycle, consequently, the charter has to be re-synced with the template...

Oh well...

Ivan
