### ISSUE TITLE
What is the relationship between the Web of Things and the Open Web Platform?

### ISSUE THREAD

**Issue by draggett** [w3c/charter-drafts#71]
In the Web of Things IG we have focused on technical issues that effect IoT platforms, but not web browsers.  Can we clarify this to avoid misunderstandings on the behalf of people working on browsers?

For instance, we have so far avoided discussion on APIs for sensors and actuators leaving these to the corresponding platforms to define.  For security APIs, it may not be so clear.

**Comment by sebastiankb** [comment]
I’m not sure if I understand your comment correctly. We have an API task force (AP-TF) in the IG that addresses this API issues. Current work assumptions can be found in the current practices document.

**Comment by mkovatsc** [comment]
So far, browser vendors were quite disinterested in the topic of IoT. Based on my Copper project, I have been in contact with people from Mozilla, Google, and the WHATWG. From what I saw, WebRTC has been their new baby so far and there was little interest to look into IoT support.

A valid comment was, that we there must be a well-defined security model before IoT support can go into the Web browser.

In my opinion, we should use the W3C to get at least one representative for one of our F2F meetings. Could we aim for something at the TPAC? For now, I would keep specifics out of the WG Charter, since we first need a specification that browser people can evaluate. I would only mention our intensions in the Coordination part.

**Comment by draggett** [comment]
Mozilla are refocusing on the IoT, Google are trying to leverage Android and their cloud based platform. I am aiming to draw in the browser vendors to the IG  when it is rechartered.  This thread can now be closed as we've moved the charter to the WoT IG repository.
